GET https://www.nbcnews.com/business/autos/tesla-loses-title-worlds-biggest-ev-maker-sales-fall-rcna251932

###
### GET request to example server
GET https://news.google.com/rss/articles/CBMipAFBVV95cUxQVlQ2ZVViQm5UV2d0OWZkV0UwNnZjRXJXdktkZFVBdGlNOFUybk9acmxUQWFCR0dJN3l1dHRTb2YtTUlsaFJQZ0Zfb1d6TzJiVlRVWlliaFI4Y0RvMzBKblh4OXVjQlRLakMtMGd6cVpmTjBNOUFPMUZaQ0pVWnRkUmgxX2NrMFhHMWJxNEw4VlFYZU9YVEdfWjNqTXRBX3ZiS3NTYw?oc=5&hl=en-US&gl=US&ceid=US:en
###

